image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - build
  - test

build and test: 
  stage: build
  script: docker-compose build && docker-compose up -d && docker-compose exec web sh -c "npm run test"
