version: '3.7'

services:
    # React
    web:
        build: .
        ports:
          - "90:9000"
        restart: always
        links:
          - mongo
    # Mongo
    mongo:
        image: mongo
        restart: always
        ports:
          - "27017:27017"