version: '3.7'

services:
    # React
    web:
        build: .
        ports:
          - "80:8000"
        restart: always
        links:
          - mongo
    # Mongo
    mongo:
        image: mongo
        restart: always
        env_file:
          - ./backend/.env 
        ports:
          - "5432:5432"